In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('/home/danbar/Desktop/project_x/health_activity_data.csv')

In [5]:
df.sort_values('Age', ascending = False)

,ID,Age,Gender,Height_cm,Weight_kg,BMI,Daily_Steps,Calories_Intake,Hours_of_Sleep,Heart_Rate,Blood_Pressure,Exercise_Hours_per_Week,Smoker,Alcohol_Consumption_per_Week,Diabetic,Heart_Disease
268,269,79,Female,161,65,27.10,14171,1310,5.0,55,111/70,1.7,No,4,No,No
273,274,79,Male,171,53,30.35,18358,2777,7.9,114,114/84,5.1,No,3,No,No
45,46,79,Female,151,115,33.16,8692,2013,5.6,59,111/83,2.6,No,1,No,No
48,49,79,Female,183,82,28.17,3440,3231,7.8,98,116/77,9.8,No,7,No,Yes
46,47,79,Male,184,74,26.80,12088,2472,6.1,74,120/81,5.9,Yes,5,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
929,930,18,Male,152,94,30.13,11846,3197,6.2,58,114/86,1.8,No,7,No,No
608,609,18,Female,196,55,22.94,6002,3494,9.6,80,136/67,4.0,No,3,No,No
605,606,18,Male,198,66,33.69,18310,3354,9.0,99,106/63,8.5,No,2,No,No
172,173,18,Female,155,73,18.79,16549,3142,6.2,83,138/71,4.4,No,3,No,No
178,179,18,Female,162,107,18.52,9924,3071,7.9,67,106/71,3.3,Yes,1,No,No